apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  namespace: mirth
  labels:
    io.kompose.service: mirth-custom-extensions
  name: mirth-custom-extensions
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 100Mi
