apiVersion: v1
kind: Service
metadata:
  namespace: mirth
  annotations:
    kompose.cmd: kompose convert
    kompose.version: 1.35.0 (HEAD)
  labels:
    io.kompose.service: mirthconnect
  name: mirthconnect
spec:
  ports:
    - name: "8443"
      port: 8443
      targetPort: 8443
    - name: "8080"
      port: 8080
      targetPort: 8080
  selector:
    io.kompose.service: mirthconnect
