apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  namespace: mirth
  labels:
    io.kompose.service: mirth-appdata
  name: mirth-appdata
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 100Mi
